name = "kimi-free-api"
main = "dist/cloudflare.js"
compatibility_date = "2024-05-01"
node_compat = true

[build]
command = "npm run build:cf"

[vars]
CLOUDFLARE_WORKER = "true"
CF_PAGES_URL = "https://your-domain.pages.dev"  # 替换为实际部署域名