name = "kimi-free-api"
main = "dist/cloudflare-native.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:cf"

[vars]
CLOUDFLARE_WORKER = "true"
TZ = "Asia/Shanghai"